name: 'google-drive-upload-git-action'
description: 'Upload files to Google Drive'
author: 'Aditya Karnam Gururaj Rao'
inputs:
  credentials:
    description: 'the service account credentials encoded in base64'
    required: true
  filename:
    description: 'the name of the file you want to upload'
    required: true
  folderId:
    description: 'the Id of the parent folder you want to upload the file in'
    required: true
  name:
    description: 'what you want the file to be called in Google Drive'
    required: false
  overwrite:
    description: 'if you want to overwrite an existing file in Google Drive '
    required: false
  

runs:
  using: docker
  image: Dockerfile
